**DATA PREPROCESSING**

In [7]:
import pandas as pd
df=pd.read_csv('data.csv')

In [8]:
df.shape

(26304, 10)

In [9]:
df.isnull().sum()

Unnamed: 0               0
brand                    0
Car_Name              3259
Engine capacity          0
Power                   22
Price                    0
Mileage                  0
Fuel_Type                0
Gearbox_Type             5
Year_Of_Production       0
dtype: int64

In [10]:
df=df.drop(columns=['Unnamed: 0'])

CHECK FOR DUPLICATES

In [11]:
df.duplicated().sum()

182

In [12]:
df[df.duplicated()]

,brand,Car_Name,Engine capacity,Power,Price,Mileage,Fuel_Type,Gearbox_Type,Year_Of_Production
105,KIA,NaN,1 598 cm3,50 KM,125 200,1 km,Benzyna,Manualna,2024
123,KIA,NaN,1 598 cm3,50 KM,125 200,1 km,Benzyna,Manualna,2024
364,KIA,NaN,1 598 cm3,50 KM,123 900,10 km,Benzyna,Manualna,2024
367,KIA,NaN,1 598 cm3,50 KM,123 900,10 km,Benzyna,Manualna,2024
369,KIA,NaN,1 598 cm3,50 KM,123 900,10 km,Benzyna,Manualna,2024
...,...,...,...,...,...,...,...,...,...
25986,OPEL,NaN,1 199 cm3,30 KM,94 900,5 km,Benzyna,Manualna,2023
26166,OPEL,Astra,1 199 cm3,30 KM,96 900,3 km,Benzyna,Manualna,2023
26167,OPEL,Astra,1 199 cm3,30 KM,96 900,3 km,Benzyna,Manualna,2023
26239,OPEL,Astra,1 199 cm3,10 KM,95 900,1 km,Benzyna,Manualna,2023
26246,OPEL,Astra,1 199 cm3,10 KM,95 900,1 km,Benzyna,Manualna,2023

In [13]:
df = df.drop_duplicates()

In [14]:
df.shape

(26122, 9)

In [15]:
df['Car_Name'].nunique()

8842

In [16]:
df['Car_Name'].fillna('others', inplace=True)

In [17]:
df.dropna(inplace=True)

In [18]:
df.isnull().sum()

brand                 0
Car_Name              0
Engine capacity       0
Power                 0
Price                 0
Mileage               0
Fuel_Type             0
Gearbox_Type          0
Year_Of_Production    0
dtype: int64

In [19]:
df['Engine_capcaity1'] = df['Engine capacity'].str[:-4]
df['Engine_Unit'] = df['Engine capacity'].str[-4:]

In [20]:
df['Power_Value'] = df['Power'].str[:-3]  # Récupère tous les caractères sauf les 3 derniers
df['Power_Unit'] = df['Power'].str[-2:]

In [21]:

df['Mileage_Value'] = df['Mileage'].str[:-3]  # Récupère tous les caractères sauf les 3 derniers
df['Mileage_Unit'] = df['Mileage'].str[-2:]

In [22]:
df = df.drop(columns=['Engine capacity','Power','Power_Unit','Engine_Unit','Mileage','Mileage_Unit'])

In [23]:
def translate_gearbox_type(polish_gearbox_type):
    translation_dict = {
        'Manualna': 'Manual',
        'Automatyczna': 'Automatic'
    }
    return translation_dict.get(polish_gearbox_type, polish_gearbox_type)

df['gearbox_type_english'] = df['Gearbox_Type'].apply(translate_gearbox_type)

In [24]:
def translate_fuel_type(polish_fuel_type):
    translation_dict = {
        'Benzyna': 'Petrol',
        'Diesel': 'Diesel',
        'Benzyna+LPG': 'Petrol+LPG',
        'Elektryczny': 'Electric',
        'Hybryda': 'Hybrid',
        'Hybryda Plug-in': 'Plug-in Hybrid'
    }
    return translation_dict.get(polish_fuel_type, polish_fuel_type)

# Example usage:
df['fuel_type_english'] = df['Fuel_Type'].apply(translate_fuel_type)

In [25]:
df=df.drop(columns=['Gearbox_Type','Fuel_Type'])

In [26]:
df.head()

,brand,Car_Name,Price,Year_Of_Production,Engine_capcaity1,Power_Value,Mileage_Value,gearbox_type_english,fuel_type_english
0,KIA,Ceed,11 650,2013,1 582,35,161 000,Manual,Diesel
1,KIA,Rio 1.4 L,33 300,2014,1 396,09,222 515,Manual,Petrol
2,KIA,Sportage 1.6 GDI M 2WD,93 500,2021,1 591,32,16 350,Manual,Petrol
3,KIA,Ceed Cee'd 1.4 Comfort +,19 750,2010,1 396,09,172 000,Manual,Petrol
4,KIA,Carens 1.7 CRDi L,48 900,2016,1 685,41,176 200,Manual,Diesel

**PRICE**

In [27]:
df['Price'] = df['Price'].str.replace(' ', '')

# Convert to float
df['Price'] = df['Price'].astype(float)

In [28]:
def convert_pln_to_dz(price_pln):
    conversion_rate = 55.20
    price_dz = price_pln * conversion_rate
    return price_dz

# Example usage:

df['price_dz'] = df['Price'].apply(convert_pln_to_dz)

In [29]:
df.drop(columns=['Price'])

,brand,Car_Name,Year_Of_Production,Engine_capcaity1,Power_Value,Mileage_Value,gearbox_type_english,fuel_type_english,price_dz
0,KIA,Ceed,2013,1 582,35,161 000,Manual,Diesel,643080.0
1,KIA,Rio 1.4 L,2014,1 396,09,222 515,Manual,Petrol,1838160.0
2,KIA,Sportage 1.6 GDI M 2WD,2021,1 591,32,16 350,Manual,Petrol,5161200.0
3,KIA,Ceed Cee'd 1.4 Comfort +,2010,1 396,09,172 000,Manual,Petrol,1090200.0
4,KIA,Carens 1.7 CRDi L,2016,1 685,41,176 200,Manual,Diesel,2699280.0
...,...,...,...,...,...,...,...,...,...
26299,OPEL,Combo,2016,1 368,5,39 800,Manual,Petrol,2456400.0
26300,OPEL,Corsa,2012,1 229,0,145 000,Manual,Petrol,1026720.0
26301,OPEL,Astra 1.6 CDTI Active,2015,1 598,10,143 000,Manual,Diesel,2257680.0
26302,OPEL,Grandland X 2.0 CDTI Edition S&S,2020,1 997,77,110 856,Automatic,Diesel,4520880.0
26303,OPEL,Corsa 1.2 City 16v,2000,1 199,5,181 000,Manual,Petrol,71760.0

**POWER VALUE**

In [30]:
df['Power_Value'] = df['Power_Value'].str.replace(' ', '')

In [31]:
df['Power_Value'].unique()

array(['35', '09', '32', '41', '36', '80', '56', 'K', '26', '50', '42',
       '0', '16', '00', '39', '45', '15', '63', '25', '77', 'KM', '22',
       '4', '40', '28', '97', '10', '60', '04', '66', '70', '84', '05',
       '85', '65', '5', 'ro', '74', '30', 'Pl', 'Ni', '83', 'So', '55',
       '92', 'EV', 'ęk', '95', 'tr', '20', '79', '9', '43', 't', '49', '',
       'RĘ', 'p', '38', '24', '81', 'n', '12', '7', '18', ',8', '54',
       '44', 'r', 'M', 'kW', 'in', 'h', 'PL', 'IN', '08', 'GT', '93', 'o',
       'kc', 'Wh', '88', 'D', '8', 'E', '02', '4k', '94', 'ws', '90', '6',
       '31', '89', '11', '01', '1', '14', '2', '07', '3', '17', 'ry',
       'eT', 'N', 'An', 'o.', 'ri', '78', 'yp', 'oe', 'li', 'ar', 'S',
       '37', 'e', '52', '72', '62', '53', '33', '99', '13', '86', '23',
       'nc', 'OS', 'l', '34', 'Q', '5,', 'TR', 'ow', '51', 'ua', '(',
       '58', 'or', '47', 'an', 'wy', '%!', 'AC', 'SO', 'I', '71', 'tb',
       'i', 'C', 'Ma', 'A', 'a', '21', '82', '48', '87', '06', '75', 'WH',
       '67', '76', '64', '46', 'PR', '03', '69', '19', '59', 'UR', '29',
       '98', 'i4', 'Dr', 've', 'i5', 'i3', 'xD', 'aś', ',', 'iX', 'i7',
       'je', '73', '91', '57', 'yA', '3%', 'ra', '27', 'to', '+', 'us',
       '61', ',s', 'cl', 'TO', 'da', 'ni', 'ze', 'ed', 'b', 'ja', 'q',
       'iu', '*', 'P', 'tk', 'LT', 'CH', 'st', 'AN', 'lt', 'ul', 'IE',
       'yż', 'R', 'NE', 'sz', 'Ba', 'Z', '.E', 'er', 'eo', 'ek', 'tn',
       'ot', 'j', 'EO', 'T', '68', '96', 'pr', 'el', 'RE', 'El', 'jm',
       'ĘK', 'CV', 'Ca', 'd', 'F', 'ęp', 'O', 'x4', 'le', 'nd', 'P6',
       'ec', 'on', 'ok', 'ss', 'g', 'G', '/', 'Sp', 'r/', 'RY', 's', '4M',
       '4m', 'ch', 'SU', '-'], dtype=object)

In [32]:
df['Power_Value']=df['Power_Value'].str.replace(',', '')

In [39]:
df['Power_Value'].unique()

array(['35', '09', '32', '41', '36', '80', '56', 'K', '26', '50', '42',
       '0', '16', '00', '39', '45', '15', '63', '25', '77', 'KM', '22',
       '4', '40', '28', '97', '10', '60', '04', '66', '70', '84', '05',
       '85', '65', '5', '74', '30', '83', '55', '92', 'EV', 'ęk', '95',
       '20', '79', '9', '43', 't', '49', '38', '24', '81', '12', '7',
       '18', '8', '54', '44', 'h', 'PL', 'IN', '08', 'GT', '93', '88',
       '02', '4k', '94', 'ws', '90', '6', '31', '89', '11', '01', '1',
       '14', '2', '07', '3', '17', 'ry', 'eT', 'N', 'An', 'o.', 'ri',
       '78', 'yp', 'oe', 'li', 'ar', 'S', '37', 'e', '52', '72', '62',
       '53', '33', '99', '13', '86', 'l', '34', 'Q', 'TR', 'ow', '51',
       'ua', '(', '58', 'or', '47', '21', '82', '48', '87', '06', '75',
       '67', '76', '64', '46'], dtype=object)

In [38]:
mode_value = df['Power_Value'].mode()[0]

# Values to replace
values_to_replace = [ 'an', 'wy', '%!', 'AC', 'SO', 'I', '71', 'tb',
       'i', 'C', 'Ma', 'A', 'a','23', 'nc', 'OS','r', 'M', 'kW', 'in', 'RĘ', 'p','Pl', 'Ni',]

# Replace values with the mode
df['Power_Value'] = df['Power_Value'].replace(values_to_replace, mode_value)

In [34]:
import numpy as np
df['Power_Value'].replace('', np.nan, inplace=True)

# Convert the 'Power_Value' column to float
df['Power_Value'] = df['Power_Value'].astype(float)

ValueError: could not convert string to float: 'K'

ENGINE CAPACITY

In [ ]:
df['Engine_capcaity1'].unique()

In [ ]:
df['Engine_capcaity1'] = df['Engine_capcaity1'].str.replace('c', '')

In [ ]:
df['Engine_capcaity1'] = df['Engine_capcaity1'].str.replace('Wejdź', '')

In [ ]:
import numpy as np
df['Engine_capcaity1'].replace('', np.nan, inplace=True)
df['Engine_capcaity1'] = df['Engine_capcaity1'].astype(float)

In [ ]:
df['Mileage_Value'] = df['Mileage_Value'].str.replace('HybrydaPlug', '')

In [ ]:
df['Mileage_Value'].replace('', np.nan, inplace=True)

df['Mileage_Value'] = df['Mileage_Value'].astype(float)

In [ ]:
df.head()

In [40]:
df.to_csv('final_data.csv')

In [41]:
df.head()

,brand,Car_Name,Price,Year_Of_Production,Engine_capcaity1,Power_Value,Mileage_Value,gearbox_type_english,fuel_type_english,price_dz
0,KIA,Ceed,11650.0,2013,1 582,35,161 000,Manual,Diesel,643080.0
1,KIA,Rio 1.4 L,33300.0,2014,1 396,09,222 515,Manual,Petrol,1838160.0
2,KIA,Sportage 1.6 GDI M 2WD,93500.0,2021,1 591,32,16 350,Manual,Petrol,5161200.0
3,KIA,Ceed Cee'd 1.4 Comfort +,19750.0,2010,1 396,09,172 000,Manual,Petrol,1090200.0
4,KIA,Carens 1.7 CRDi L,48900.0,2016,1 685,41,176 200,Manual,Diesel,2699280.0

In [42]:
df['Car_Name'].nunique()

8841

In [ ]:
!pip install --upgrade scikit-learn

In [ ]:
import sklearn
print(sklearn.__version__)

In [ ]:
import pandas as pd
df=pd.read_csv('final_data.csv')

In [ ]:
df.head()

In [ ]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [ ]:
new_data = {
    "brand": "KIA",
    "Car_Name": "Ceed",
    "Engine_capcaity1": 11650.0,
    "Year": 2013,
    "Power_Value": 1582.0,
    "Mileage_Value": 35.0,
    "gearbox_type_english": "Manual",
    "fuel_type_english": "Diesel"
}

# Encode the categorical features
new_data["gearbox_type_english"] = gearbox.transform([new_data["gearbox_type_english"]])[0]
new_data["brand"] = bran.transform([new_data["brand"]])[0]
new_data["fuel_type_english"] = fuel.transform([new_data["fuel_type_english"]])[0]
new_data["Car_Name"] = carn.transform([new_data["Car_Name"]])[0]

In [ ]:
from sklearn.preprocessing import LabelEncoder
gearbox = LabelEncoder()
df["gearbox_type_english"] = gearbox.fit_transform(df["gearbox_type_english"])
df["gearbox_type_english"].unique()

In [ ]:


new_data = {
    "brand": "KIA",
    "Car_Name": "Ceed",
    "Engine_capcaity1": 11650.0,
    "Year": 2013,
    "Power_Value": 1582.0,
    "Mileage_Value": 35.0,
    "gearbox_type_english": "Manual",
    "fuel_type_english": "Diesel"
}

# Encode the categorical features
new_data["gearbox_type_english"] = gearbox.transform([new_data["gearbox_type_english"]])[0]

print(new_data)

In [ ]:
bran= LabelEncoder()
df["brand"] = bran.fit_transform(df["brand"])
df["brand"].unique()

In [ ]:
# prompt: encode it using bran

new_data["brand"] = bran.transform([new_data["brand"]])[0]
print(new_data)

In [ ]:
fuel = LabelEncoder()
df["fuel_type_english"] = fuel.fit_transform(df["fuel_type_english"])
df["fuel_type_english"].unique()

In [ ]:
print(new_data)

In [ ]:
carn = LabelEncoder()
df["Car_Name"] = carn.fit_transform(df["Car_Name"])
df["Car_Name"].unique()

In [ ]:
# prompt: encode it using carn and display it

new_data["Car_Name"] = carn.transform([new_data["Car_Name"]])[0]

print(new_data)

In [ ]:
df.head()

In [ ]:
df.drop(columns=['Price'])

In [ ]:
df.isnull().sum()

In [ ]:
df.dropna(inplace=True)

In [ ]:
X = df.drop('price_dz', axis=1)
y = df['price_dz']

In [ ]:
X.shape

In [ ]:
# prompt: drop column Price

df.drop(columns=['Price'], inplace=True)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=4)
X_reduced = pca.fit_transform(X_scaled)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_reduced, y, test_size=0.3, random_state=42)

# Train the Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = model.predict(X_test)

# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean squared error: {mse}")
print(f"R2 score: {r2}")

In [ ]:
# prompt: apply xgboost

import xgboost as xgb

# Convert the data into DMatrix format
dtrain = xgb.DMatrix(data=X_train, label=y_train)
dtest = xgb.DMatrix(data=X_test, label=y_test)

# Define the XGBoost parameters
params = {
    'objective': 'reg:squarederror',
    'colsample_bytree': 0.3,
    'learning_rate': 0.3,
    'max_depth': 5,
    'alpha': 10
}

# Train the XGBoost model
model = xgb.train(params=params, dtrain=dtrain, num_boost_round=50)

# Make predictions on the testing set
y_pred = model.predict(dtest)

# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean squared error: {mse}")
print(f"R2 score: {r2}")

In [ ]:
# prompt: use search grid

from sklearn.model_selection import GridSearchCV

# Define the hyperparameter grid
param_grid = {
    'learning_rate': [0.1, 0.3, 0.5],
    'max_depth': [3, 5, 7],
    'alpha': [1, 10, 100]
}

# Create a grid search object
grid_search = GridSearchCV(estimator=xgb.XGBRegressor(objective='reg:squarederror'), param_grid=param_grid, cv=5)

# Fit the grid search object to the training data
grid_search.fit(X_train, y_train)

# Get the best model
best_model = grid_search.best_estimator_

# Make predictions on the testing set
y_pred = best_model.predict(X_test)

# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean squared error: {mse}")
print(f"R2 score: {r2}")

In [ ]:

from sklearn.ensemble import RandomForestRegressor

# Create a random forest regressor model
model = RandomForestRegressor()

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean squared error: {mse}")
print(f"R2 score: {r2}")

In [ ]:

# Tune the hyperparameters of the Random Forest Regressor using GridSearchCV
from sklearn.model_selection import GridSearchCV

# Define the hyperparameter grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Create a grid search object
grid_search = GridSearchCV(estimator=RandomForestRegressor(), param_grid=param_grid, cv=5)

# Fit the grid search object to the training data
grid_search.fit(X_train, y_train)

# Get the best model
best_model = grid_search.best_estimator_

# Make predictions on the testing set
y_pred = best_model.predict(X_test)

# Evaluate the model performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean squared error: {mse}")
print(f"R2 score: {r2}")

**un MSE bas et un R2 score élevé sont généralement des indicateurs de bonnes

*   List item
*   List item

performances du modèle**

In [ ]:
import pickle

In [ ]:
saved_data = {
    "model": model,  # Votre modèle entraîné
    "gearbox_encoder": gearbox,
    "brand_encoder": bran,
    "fuel_encoder": fuel,
    "Car_Name_encoder": carn,
    "scaler": scaler,
    "pca": pca
}

# Sauvegarder les étapes de prétraitement et le modèle dans un fichier
with open('saved_steps.pkl', 'wb') as file:
    pickle.dump(saved_data, file)

In [ ]:
import pickle
with open('saved_steps.pkl', 'rb') as file:
    loaded_data = pickle.load(file)

In [ ]:
import numpy as np
import pickle
with open('saved_steps.pkl', 'rb') as file:
    loaded_data = pickle.load(file)

new_data = {
    "brand": "KIA",
    "Car_Name": "Ceed",
    "Engine_capcaity1": 11650.0,
    "Year": 2013,
    "Power_Value": 1582.0,
    "Mileage_Value": 35.0,
    "gearbox_type_english": "Manual",
    "fuel_type_english": "Diesel"
}

# Encode the categorical features
new_data["gearbox_type_english"] = gearbox.transform([new_data["gearbox_type_english"]])[0]
new_data["brand"] = bran.transform([new_data["brand"]])[0]
new_data["fuel_type_english"] = fuel.transform([new_data["fuel_type_english"]])[0]
new_data["Car_Name"] = carn.transform([new_data["Car_Name"]])[0]

# Convert the data to a NumPy array
new_data_array = np.array([list(new_data.values())])

# Standardize the data
new_data_scaled = scaler.transform(new_data_array)

# Reduce the dimensionality of the data
new_data_reduced = pca.transform(new_data_scaled)

# Predict the price
predicted_price = model.predict(new_data_reduced)[0]

# Print the predicted price
print(f"Predicted price: {predicted_price}")